export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILD = 'FETCH_INGREDIENTS_FAILD';

export const ORDER_PURCHASE_START = 'ORDER_PURCHASE_START';
export const ORDER_PURCHASE_SUCCESS = 'ORDER_PURCHASE_SUCCESS';
export const ORDER_PURCHASE_FAIL = 'ORDER_PURCHASE_FAIL';
export const ORDER_PURCHASE_REDIRECT = 'ORDER_PURCHASE_REDIRECT';

export const FETCH_ORDER_START = 'FETCH_ORDER_START';
export const FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS';
export const FETCH_ORDER_FAIL = 'FETCH_ORDER_FAIL';